baseURL = "https://honghe.github.io/blog2/"
languageCode = "zh-cn"
title = "Jack's Blog"
theme = "hugo-primer"

paginate = 200
hasCJKLanguage = true
summaryLength = 30

uglyURLs = true

RelativeURLs = true
CanonifyURLs = true